# Generated by Django 5.2.6 on 2025-09-07 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plant_type', models.CharField(choices=[('F', 'Flower'), ('C', 'Cactus'), ('T', 'Tree'), ('S', 'Succulent'), ('H', 'Herb'), ('V', 'Vegetable'), ('O', 'Other')], default='F', max_length=1)),
                ('watering_frequency', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('B', 'Bi-weekly'), ('M', 'Monthly'), ('R', 'Rarely')], default='D', max_length=1)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
